### ISSUE TITLE
Support Ticket - button is greyed out in case of emtpy fields

### ISSUE THREAD

**Issue by theaamanda** [leapcode/leap_web#227]
Steps to reproduce:
- view of support tickets
- click "New Ticket"
- leave the fields empty
- click "Submit Ticket"
- --> "Submit Ticket" is "Loading" and greyed out, have refresh to fill the regarding fields to submit ticket

**Comment by theaamanda** [comment]
bug is not existing for demo.bitmask.net

**Comment by azul** [comment]
Thanks for the report. This was not an issue on demo back in the days but now we are deploying there too.
Still benefiting from your contributions :sunflower:
