### ISSUE TITLE
admin view for non-admin shown 

### ISSUE THREAD

**Issue by theaamanda** [leapcode/leap_web#233]
- be logged in as a normal user to webapp
- log in as an admin in new tab
- switch back to non-admin
  -> email and stuff is still shown for non-admin but the view is as for admins, refreshing then shows all the data of admin

**Comment by azul** [comment]
:thought_balloon: hmmm.... :grey_question: we authenticate users based on cookies in the browser. These are shared across tabs. That way you can login in one tab and open a link in a different tab and still be logged in. This is the way most sites handle this.

You can probably try the same with other sites such as github. If you look at your repo without being logged in and then log in in a different tab a reload in your repo tab will also show you as logged in.
I don't see any way around this.
